### ISSUE TITLE
Any more details?

### ISSUE THREAD

**Issue by srsudar** [go-shiori/warc#1]
I'm a bit confused as to what WARC is doing. Is it kind of like a bespoke version of [web bundles](https://web.dev/web-bundles/)? 

I've been messing around with Shiori and really like it. Just trying to get a better handle on how it all works.

**Comment by RadhiFadlillah** [comment]
@srsudar sorry for late reply.

Well, `warc` is package to archive a web page and save it as a single file, in this case a [`bolt`](https://github.com/etcd-io/bbolt) database. It's kind of similar with [`monolith`](https://github.com/Y2Z/monolith) with few differences :

- `monolith` is built with Rust, while `warc` is in Go.
- `monolith` archive a web page as single HTML file, while `warc` archive it as a `bolt` database.
- IIRC `monolith` fetch web page resources synchronously, while `warc` do it asynchronously thanks to goroutine, so usually `warc` will be faster than `monolith`.
- `monolith` is more stable though, in fact right now I'm trying to learn how `monolith` make a better archive than `warc` in some page, e.g. for Github.com.

This is the first time I heard about web bundles, so I can't compare it with `warc`.

**Comment by srsudar** [comment]
Ah interesting. I'm more used to `mhtml` files as an archive format, but both of these do look cool. I was messing around with a `shiori` fork and was confused by `warc`.

Makes more sense now, thanks!
